# Generated by Django 3.0.7 on 2020-06-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='description of item goes here'),
            preserve_default=False,
        ),
    ]
