# Generated by Django 3.0.7 on 2020-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200617_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
